# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
resolver = "2"
members = ["crates/limnus-steam-input", "crates/limnus-steamworks",
    "crates/mangrove",
    "crates/save-detector",
    "crates/script",
]
