[package]
name = "mangrove-script"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "Swamp Script plugin for Mangrove"
repository = "https://github.com/swamp/mangrove"

[dependencies]
swamp = { path = "../../../swamp/crates/swamp", version = "0.0.13" }

# Swamp Script
swamp-script = { path = "../../../script/crates/swamp-script", version = "0.0.4" }
swamp-script-eval-loader = { path = "../../../script/crates/eval-loader", version = "0.0.4" }
swamp-script-parser = { path = "../../../script/crates/parser", version = "0.0.4" }
swamp-script-semantic = { path = "../../../script/crates/semantic", version = "0.0.4" }
swamp-script-eval = { path = "../../../script/crates/eval", version = "0.0.4" }

tracing = "0.1.41"
seq-map = "0.0.11"

pest = "2.7.14"
monotonic-time-rs = "0.0.5"
