[package]
name = "mangrove-script"
version = "0.0.4-alpha.2"
edition = "2021"
license = "MIT"
description = "Swamp Script plugin for Mangrove"
repository = "https://github.com/swamp/mangrove"

[dependencies]

swamp = { path = "../../../swamp/crates/swamp", version="0.0.14-alpha.1" }
#swamp = "0.0.14-alpha.1"

swamp-script = { path = "../../../script/crates/swamp-script", version = "0.0.8" }
# swamp-script = "0.0.8"

limnus-message = "0.0.12"
limnus-gamepad = "0.0.12"

tracing = "0.1.41"
seq-map = "0.0.13"
monotonic-time-rs = "0.0.5"
