[package]
name = "mangrove-script"
version = "0.0.2"
edition = "2021"
license = "MIT"
description = "Swamp Script plugin for Mangrove"
repository = "https://github.com/swamp/mangrove"

[dependencies]
swamp = "0.0.13"
limnus-message = "0.0.12"

# Swamp Script
swamp-script = "0.0.4"
swamp-script-eval-loader = "0.0.4"
swamp-script-parser = "0.0.4"
swamp-script-semantic = "0.0.4"
swamp-script-eval = "0.0.4"

tracing = "0.1.41"
seq-map = "0.0.11"
pest = "2.7.14"
monotonic-time-rs = "0.0.5"
