[package]
name = "mangrove-script"
version = "0.0.2"
edition = "2021"
license = "MIT"
description = "Swamp Script plugin for Mangrove"
repository = "https://github.com/swamp/mangrove"

[dependencies]
# swamp = { path = "../../../swamp/crates/swamp" }
swamp = { path = "../../../swamp/crates/swamp" }

limnus-message = "0.0.12"
limnus-gamepad = "0.0.12"

# Swamp Script
swamp-script = { path = "../../../script/crates/swamp-script" }
swamp-script-eval-loader = { path = "../../../script/crates/eval-loader" }
swamp-script-parser = { path = "../../../script/crates/parser" }
swamp-script-semantic = { path = "../../../script/crates/semantic" }
swamp-script-eval = { path = "../../../script/crates/eval" }
swamp-script-core = { path = "../../../script/crates/core" }
swamp-script-std = { path = "../../../script/crates/std" }
swamp-script-derive = { path = "../../../script/crates/derive" }

tracing = "0.1.41"
seq-map = "0.0.13"
pest = "2.7.14"
monotonic-time-rs = "0.0.5"
