[package]
name = "limnus-steamworks"
version = "0.0.9"
edition = "2024"

[dependencies]
steamworks = "0.11.0"
limnus-app = "0.0.16"
limnus-local-resource = "0.0.16"
limnus-resource = "0.0.16"
limnus-system-params = "0.0.16"
limnus-default-stages = "0.0.16"

tracing = "0.1.40"
