[package]
name = "mangrove-engine"
version = "0.0.5"
edition = "2021"
license = "MIT"
description = "2D game engine powered by swamp-script"
repository = "https://github.com/swamp/mangrove"

[[bin]]
name = "mangrove"
path = "src/main.rs"

[dependencies]
swamp = "0.0.15"
# swamp = { path = "../../../swamp/crates/swamp", version = "0.0.15" }

mangrove-script = { path = "../script", version = "0.0.5" }
mangrove-save-detector = { path = "../save-detector", version = "0.0.5" }
