[package]
name = "mangrove"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "2D game engine powered by swamp-script"
repository = "https://github.com/swamp/mangrove"

[dependencies]
swamp = { path = "../../../swamp/crates/swamp", version = "0.0.12" }

mangrove-script = { path = "../script", version = "0.0.1"}

tracing = "0.1.41"
seq-map = "0.0.11"

pest = "2.7.14"
