[package]
name = "limnus-input-binding"
version = "0.0.16"
edition = "2024"

[dependencies]
seq-map = "0.0.13"
limnus-app = "0.0.17"
limnus-local-resource = "0.0.17"
limnus-resource = "0.0.17"
limnus-system-params = "0.0.17"
limnus-default-stages = "0.0.17"
