[package]
name = "mangrove-save-detector"
version = "0.0.2"
edition = "2021"
license = "MIT"
description = "Detects file changes and sends message to mangrove script plugin"
repository = "https://github.com/swamp/mangrove"

[dependencies]
notify = "7.0.0"
swamp = { path = "../../../swamp/crates/swamp" }
limnus-message = "0.0.12"
message-channel = "0.0.1"
mangrove-script = { path = "../script", version = "0.0.2" }
